[irc.twitch]
#Add the oauth token here you got from https://twitchapps.com/tmi/
#Password="oauth:yourtoken"
Nick="justinfan1337"
Server="irc.chat.twitch.tv:6697"
UseTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

ShowJoinPart=false
NoSendJoinPart=true

[irc.freenode]
Nick="vs_bridge"
Server="chat.freenode.net:6697"
UseTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

ShowJoinPart=false
NoSendJoinPart=true

###################################################################
#API
###################################################################
[api]
##You can configure multiple API hooks
##In this example we use [api.local]
##REQUIRED

[api.vintagestory]
#Address to listen on for API
#REQUIRED 
BindAddress="0.0.0.0:4242"

#Bearer token used for authentication
#curl -H "Authorization: Bearer secret" http://nikky.moe:4242/api/messages
#OPTIONAL (no authorization if token is empty)
Token="token12345"

#Amount of messages to keep in memory
Buffer=1000

# RemoteNickFormat defines how remote users appear on this bridge 
# The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
# The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
# The string "{LABEL}" (case sensitive) will be replaced by Label= field of the sending bridge
# The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
# OPTIONAL (default empty)
RemoteNickFormat="{NICK}"
ShowJoinPart = true

#extra label that can be used in the RemoteNickFormat
#optional (default empty)
Label="api.vintagestory"

[[gateway]]
name="general"
enable=true
inout = [
    { account="irc.freenode", channel="#matterbridge-test" },
    { account="api.vintagestory", channel="api" }
]

[[gateway]]
name="twitch_copygirl"
enable=true
in = [
    { account="irc.twitch", channel="#copygirl" }
]
out = [
    { account="api.vintagestory", channel="api" }
]

[[gateway]]
name="twitch_lunarlight"
enable=true
in = [
    { account="irc.twitch", channel="#lunarlight" }
]
out = [
    { account="api.vintagestory", channel="api" }
]

[[gateway]]
name="twitch_kainei"
enable=true
in = [
    { account="irc.twitch", channel="#kainei" }
]
out = [
    { account="api.vintagestory", channel="api" }
]
    
