on:
  push:
    branches:
     - master

name: Create Release Snapshot

jobs:
  build:
    name: Create Release Snapshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet build
      - name: Set enviroment for github-release
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "VERSION=$(cat modinfo.json | jq .version)" >> $GITHUB_ENV
      - name: Set enviroment RELEASE_TAG
        run: |
          echo "RELEASE_TAG=snapshot/${{ env.VERSION }}-${{ env.BRANCH }}-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: print env
        run: |
          echo "BRANCH=${{ env.BRANCH }}"
          echo "VERSION=${{ env.VERSION }}"
          echo "RELEASE_TAG=${{ env.RELEASE_TAG }}"
      - name: Create prerelease
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          commitish: ${{ env.GITHUB_SHA }}
          name: ${{ env.VERSION }}
          prerelease: true
          body: Snapshot Release ${{ env.VERSION }}
          gzip: folders
          files: >
            Matterbridge.zip:bin/Matterbridge.zip
