#WARNING: as this file contains credentials, be sure to set correct file permissions
[irc]
[irc.freenode]
Server="chat.freenode.net:6667"
Nick="matterbot"

UseTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

ShowJoinPart=false
NoSendJoinPart=true

[api.vintagestory]
#Address to listen on for API
#REQUIRED
BindAddress="0.0.0.0:4242"

#Bearer token used for authentication
#curl -H "Authorization: Bearer secret" http://nikky.moe:4242/api/messages
#OPTIONAL (no authorization if token is empty)
Token="5YZJgQwRb4nzMgLicMFn"

#Amount of messages to keep in memory
Buffer=1000

# RemoteNickFormat defines how remote users appear on this bridge
# The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
# The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
# The string "{LABEL}" (case sensitive) will be replaced by Label= field of the sending bridge
# The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
# OPTIONAL (default empty)
RemoteNickFormat="{NICK}"
ShowJoinPart = true

#extra label that can be used in the RemoteNickFormat
#optional (default empty)
Label="api.vintagestory"

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.freenode"
channel="#test_matterbridge"

[[gateway.inout]]
account="api.vintagestory"
channel="api"

[[gateway]]
name="oneway"
enable=true
[[gateway.in]]
account="irc.freenode"
channel="#test_matterbridge_oneway"

[[gateway.out]]
account="api.vintagestory"
channel="api"

#simpler config possible since v0.10.2
[[gateway]]
name="short"
enable=true
inout = [
    { account="irc.freenode", channel="#test_matterbridge_offtopic", options={key="channelkey"}},
    { account="api.vintagestory", channel="api" },
]